name: Loader pipeline
on:
  push:
  workflow_dispatch:

env:
  API_BASE_URL: http://localhost:3000
  # That token expires in 24h, don't fret
  VERCEL_TOKEN: t4kQK1xr3Xqqn6H0CD2z04RL

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"

      - run: npm install -g vercel

      - name: Start Vercel dev server
        run: |
          npx vercel dev --token ${{ env.VERCEL_TOKEN }} --confirm &
          # Store the PID to use later if needed
          echo "VERCEL_PID=$!" >> $GITHUB_ENV
          
          # Wait for server to be ready on port 3000
          timeout=60
          counter=0
          echo "Waiting for server to be ready on port 3000..."
          until $(curl --output /dev/null --silent --fail http://localhost:3000); do
            if [ $counter -eq $timeout ]; then
              echo "Timed out waiting for server to start"
              exit 1
            fi
            counter=$((counter+1))
            echo "Still waiting for server to be ready... ($counter/$timeout)"
            sleep 1
          done
          echo "Server is ready!"

      - run:
          response=$(curl -s ${{ env.API_BASE_URL }}/api/echo) &&
          echo $response